/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Component;
import javax.swing.JFrame;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author AVLip
 */
public class ViwSistema extends javax.swing.JFrame {

    /**
     * Creates new form ViwSistema
     */
    public ViwSistema() {
        initComponents();
        this.setVisible(true);
        
        setCurrentPanel("panLogin");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLogin = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        linkCadastroUsuario = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        panCadastroUsuario = new javax.swing.JPanel();
        labUsuarioCadastro = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtTelefoneUsuario = new javax.swing.JTextField();
        txtEmailUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JTextField();
        btnGravarUsuario = new javax.swing.JButton();
        panHome = new javax.swing.JPanel();
        txtPrecaucao1 = new javax.swing.JTextArea();
        txtPrecaucao2 = new javax.swing.JTextArea();
        txtPrecaucao3 = new javax.swing.JTextArea();
        txtPrecaucao4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 200, 250));

        panLogin.setBackground(new java.awt.Color(255, 255, 255));
        panLogin.setName("panLogin"); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtUsuario.setToolTipText("Usuário");
        txtUsuario.setName("txtUsuario"); // NOI18N

        linkCadastroUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        linkCadastroUsuario.setText("Cadastre-se");
        linkCadastroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        linkCadastroUsuario.setName("linkCadastro"); // NOI18N

        txtSenha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtSenha1.setName("txtSenha1"); // NOI18N

        btnEntrar.setBackground(new java.awt.Color(80, 80, 250));
        btnEntrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar.setName("btnEntrar"); // NOI18N

        javax.swing.GroupLayout panLoginLayout = new javax.swing.GroupLayout(panLogin);
        panLogin.setLayout(panLoginLayout);
        panLoginLayout.setHorizontalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLoginLayout.createSequentialGroup()
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(linkCadastroUsuario))
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(txtSenha1)))
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panLoginLayout.setVerticalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLoginLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkCadastroUsuario)
                .addGap(65, 65, 65))
        );

        panCadastroUsuario.setName("panCadastroUsuario"); // NOI18N

        labUsuarioCadastro.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        labUsuarioCadastro.setText("Nome");

        txtNomeUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtNomeUsuario.setToolTipText("Usuário");
        txtNomeUsuario.setName("txtNomeUsuario"); // NOI18N

        txtTelefoneUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtTelefoneUsuario.setToolTipText("Usuário");
        txtTelefoneUsuario.setName("txtTelefoneUsuario"); // NOI18N

        txtEmailUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtEmailUsuario.setToolTipText("Usuário");
        txtEmailUsuario.setName("txtEmailUsuario"); // NOI18N

        txtSenhaUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtSenhaUsuario.setToolTipText("Usuário");
        txtSenhaUsuario.setName("txtSenhaUsuario"); // NOI18N

        btnGravarUsuario.setBackground(new java.awt.Color(80, 80, 250));
        btnGravarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnGravarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGravarUsuario.setText("Confirmar");
        btnGravarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGravarUsuario.setName("btnEntrar"); // NOI18N

        javax.swing.GroupLayout panCadastroUsuarioLayout = new javax.swing.GroupLayout(panCadastroUsuario);
        panCadastroUsuario.setLayout(panCadastroUsuarioLayout);
        panCadastroUsuarioLayout.setHorizontalGroup(
            panCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadastroUsuarioLayout.createSequentialGroup()
                .addGroup(panCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnGravarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panCadastroUsuarioLayout.setVerticalGroup(
            panCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(labUsuarioCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtTelefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnGravarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        panHome.setName("panHome"); // NOI18N

        txtPrecaucao1.setBackground(new java.awt.Color(200, 210, 255));
        txtPrecaucao1.setColumns(20);
        txtPrecaucao1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtPrecaucao1.setRows(5);

        txtPrecaucao2.setBackground(new java.awt.Color(150, 200, 250));
        txtPrecaucao2.setColumns(20);
        txtPrecaucao2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtPrecaucao2.setRows(5);

        txtPrecaucao3.setBackground(new java.awt.Color(150, 200, 250));
        txtPrecaucao3.setColumns(20);
        txtPrecaucao3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtPrecaucao3.setRows(5);

        txtPrecaucao4.setBackground(new java.awt.Color(200, 210, 250));
        txtPrecaucao4.setColumns(20);
        txtPrecaucao4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtPrecaucao4.setRows(5);

        jButton1.setBackground(new java.awt.Color(80, 80, 250));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("=");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.PNG"))); // NOI18N

        javax.swing.GroupLayout panHomeLayout = new javax.swing.GroupLayout(panHome);
        panHome.setLayout(panHomeLayout);
        panHomeLayout.setHorizontalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panHomeLayout.createSequentialGroup()
                        .addComponent(txtPrecaucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecaucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panHomeLayout.createSequentialGroup()
                        .addComponent(txtPrecaucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecaucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        panHomeLayout.setVerticalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHomeLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecaucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecaucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecaucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecaucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panCadastroUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panCadastroUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addListenerBtnEntrar(ActionListener action){
       this.btnEntrar.addActionListener(action);
    }
    
    public void addListenerLinkCadastro(MouseAdapter action){
        this.linkCadastroUsuario.addMouseListener(action);
    }
    
    public void addListenerBtnGravarUsuario(ActionListener action){
        this.btnGravarUsuario.addActionListener(action);
    }
    
    public Map getFieldsByPanel(String panelName){
        Map valores = new HashMap<String, String>();
        for (Component C : this.getContentPane().getComponents()) {
            if (C instanceof JPanel && C.getName() != null && C.getName().equalsIgnoreCase(panelName)) {
                JPanel P = (JPanel) C;
                for (Component T : P.getComponents()) {
                    if (T instanceof JTextField) {
                        valores.put(T.getName(),((JTextComponent) T).getText());
                    }
                }
            }
        }
        return valores;
    }
    
    public void setCurrentPanel(String panelName){
        
        for (Component C : this.getContentPane().getComponents()) {
            if (C instanceof JPanel) {
                JPanel P = (JPanel) C;
                if (P.getName().equalsIgnoreCase(panelName)) {
                    P.setVisible(true);
                } else {
                    P.setVisible(false);
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnGravarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labUsuarioCadastro;
    private javax.swing.JLabel linkCadastroUsuario;
    private javax.swing.JPanel panCadastroUsuario;
    private javax.swing.JPanel panHome;
    private javax.swing.JPanel panLogin;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextArea txtPrecaucao1;
    private javax.swing.JTextArea txtPrecaucao2;
    private javax.swing.JTextArea txtPrecaucao3;
    private javax.swing.JTextArea txtPrecaucao4;
    private javax.swing.JPasswordField txtSenha1;
    private javax.swing.JTextField txtSenhaUsuario;
    private javax.swing.JTextField txtTelefoneUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
